### ISSUE TITLE
use of internal package not allowed!

### ISSUE THREAD

**Issue by taoyunxing** [lucas-clemente/quic-go#1211]
I run the two cmds on Ubuntu 16.04.3 LTS and go 1.10，but found this following errors:
`go run example/main.go -www /var/www/
example/main.go:22:2: use of internal package not allowed
example/main.go:23:2: use of internal package not allowed
go run example/client/main.go https://clemente.io
example/client/main.go:12:2: use of internal package not allowed
example/client/main.go:13:2: use of internal package not allowed`

please help me， thanks in advance！

**Comment by marten-seemann** [comment]
Sounds like there's a problem with your GOPATH. Can you check that you correctly installed quic-go in your GOPATH?

**Comment by Al-Dailami** [comment]
I have a problem with the client when starting the client 
go run client/main.go  https://localhost:6121
GET https://localhost:6121
Starting new connection to localhost ([::]:59957 -> 127.0.0.1:6121), connectionID 1ea0096b23d63160, version gQUIC 39
Certificate validation failed: x509: certificate is valid for quic.clemente.io, not localhost
Closing session with error: ProofInvalid
panic: Get https://localhost:6121: ProofInvali


The Server IS RUNNING and the output after the client request is:
Serving new connection: 1ea0096b23d63160, version gQUIC 39 from 127.0.0.1:59957
Closing session with error: ProofInvalid:

**Comment by Al-Dailami** [comment]
How can i test the server???

I want to test the local server 

By the way, When i changed the request to https://quic.clemente.io the following ERROR occurred 

GET https://quic.clemente.io
Starting new connection to quic.clemente.io ([::]:53814 -> 188.68.52.107:443), connectionID ca06155e9ba394b4, version gQUIC 39
Received a Version Negotiation Packet. Supported Versions: [gQUIC 37 gQUIC 36 gQUIC 35]
Closing session with error: InvalidVersion
Connection ca06155e9ba394b4 closed.
panic: Get https://quic.clemente.io: InvalidVersion

goroutine 19 [running]:
main.main.func1(0xc420093350, 0xc4200a45a0, 0x7ffca6579188, 0x18)
        /home/csu/eclipse-workspace/QUIC_GO/src/github.com/lucas-clemente/quic-go/example/client/main.go:49 +0x565
created by main.main
        /home/csu/eclipse-workspace/QUIC_GO/src/github.com/lucas-clemente/quic-go/example/client/main.go:46 +0x6c5

**Comment by marten-seemann** [comment]
Same as you would use a HTTPS server in Go. You will need to provide your own certificate.

**Comment by Al-Dailami** [comment]
Thanks a lot for your help.. 

Actually I'm new to Go.  Can you recommend some resources that can help me configuring the QUIC Server and Client. 

Thanks again in advance

**Comment by marten-seemann** [comment]
There's nothing special about configuring the QUIC server and client. Please first setup a HTTPS server and client and make sure that works. There are plenty of tutorials for that around on the internet. Once that works, switching to QUIC is trivial (refer to the example for the necessary code).
