### ISSUE TITLE
Panic in packet packer

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#133]
Got this when loading a 100MB file with the client. Reproducible in about 50% of the tries:

    ~/src/chromium/src/out/Debug/quic_client --quic-version=30 --host=127.0.0.1 --port=6121 https://quic.clemente.io/foo &> /dev/null

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x2c21f8]

goroutine 50 [running]:
panic(0x449620, 0xc8200140e0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/lucas-clemente/quic-go.(*packetPacker).composeNextPacket(0xc8200a6820, 0x0, 0xa, 0xc801, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/lucas/src/go/src/github.com/lucas-clemente/quic-go/packet_packer.go:165 +0x248
github.com/lucas-clemente/quic-go.(*packetPacker).PackPacket(0xc8200a6820, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc8203e4780, 0x0, 0x0)
	/Users/lucas/src/go/src/github.com/lucas-clemente/quic-go/packet_packer.go:101 +0x41a
github.com/lucas-clemente/quic-go.(*Session).sendPacket(0xc8200a8a00, 0x0, 0x0)
	/Users/lucas/src/go/src/github.com/lucas-clemente/quic-go/session.go:492 +0x765
github.com/lucas-clemente/quic-go.(*Session).maybeSendPacket(0xc8200a8a00, 0x0, 0x0)
	/Users/lucas/src/go/src/github.com/lucas-clemente/quic-go/session.go:406 +0xbf
github.com/lucas-clemente/quic-go.(*Session).run(0xc8200a8a00)
	/Users/lucas/src/go/src/github.com/lucas-clemente/quic-go/session.go:193 +0x5f0
created by github.com/lucas-clemente/quic-go.(*Server).handlePacket
	/Users/lucas/src/go/src/github.com/lucas-clemente/quic-go/server.go:144 +0x92a
exit status 2
```

**Comment by marten-seemann** [comment]
Only with QUIC 30 or also with more recent version?

**Comment by lucas-clemente** [comment]
Independent of the version, can also repro with 32.

**Comment by marten-seemann** [comment]
Please test again, too see if 57066fa also fixed this issue.

**Comment by lucas-clemente** [comment]
Seems so. Closing. :)
