### ISSUE TITLE
another Panic in PacketPacker

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#134]
Happens every ~5% of the tests.

```
panic: runtime error: slice bounds out of range

goroutine 70 [running]:
panic(0x33b300, 0xc82000c230)
	/usr/local/Cellar/go/HEAD/libexec/src/runtime/panic.go:500 +0x18c
github.com/lucas-clemente/quic-go.(*packetPacker).composeNextPacket(0xc820300e60, 0x0, 0xa, 0xc82048f601, 0x0, 0x0, 0xc820045a78, 0x4f380, 0xc820314000)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/packet_packer.go:171 +0x1cd
github.com/lucas-clemente/quic-go.(*packetPacker).PackPacket(0xc820300e60, 0x0, 0x0, 0x0, 0x0, 0xc820309601, 0x37d5e0, 0x185ef4, 0x2)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/packet_packer.go:101 +0x266
github.com/lucas-clemente/quic-go.(*Session).sendPacket(0xc8201bb180, 0x376c36a1, 0x5621e0)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:492 +0x329
github.com/lucas-clemente/quic-go.(*Session).maybeSendPacket(0xc8201bb180, 0xc82001c3c0, 0x0)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:406 +0x89
github.com/lucas-clemente/quic-go.(*Session).run(0xc8201bb180)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:193 +0x3ad
created by github.com/lucas-clemente/quic-go.glob.func7.5.1
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session_test.go:295 +0x6c
exit status 2
```

**Comment by marten-seemann** [comment]
I ran the tests 100 times and it didn't occur again, so I think it's fixed.
