### ISSUE TITLE
Deadlock between onStreamCompleted and Session.Close

### ISSUE THREAD

**Issue by ltucker** [lucas-clemente/quic-go#1364]
There appears to be a deadlock between calling `Session.Close(...)` and various `Stream` calls (eg `Read`) which may trigger a call to `onStreamCompleted` while holding a Stream lock.  They each hold a lock the other needs since they acquire them in different orders (eg legacy_stream_map lock and receive_stream lock)

Here is a (finnecky, contrived) reproduction of a particular instance of this problem: [deadlock_test.go](https://gist.github.com/ltucker/0480861abc84592f32da3a8dfe4957fb)

When it hits the issue, the goroutines are deadlocked like this:

[Full output](https://gist.github.com/ltucker/7779a7d31634fb77312929d37a788e13)
```
goroutine 107673 [semacquire, 9 minutes]:
sync.runtime_SemacquireMutex(0xc420740384, 0x0)
    /usr/local/Cellar/go/1.10/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420740380)
    /usr/local/Cellar/go/1.10/libexec/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0xc420740380)
    /usr/local/Cellar/go/1.10/libexec/src/sync/rwmutex.go:93 +0x2d
github.com/lucas-clemente/quic-go.(*streamsMapLegacy).DeleteStream(0xc420740380, 0x2d, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/streams_map_legacy.go:224 +0x39
github.com/lucas-clemente/quic-go.(*session).onStreamCompleted(0xc420711400, 0x2d)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/session.go:1219 +0x3e
github.com/lucas-clemente/quic-go.(*stream).checkIfCompleted(0xc420654000)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/stream.go:173 +0x6f
github.com/lucas-clemente/quic-go.newStream.func2()
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/stream.go:119 +0x52
github.com/lucas-clemente/quic-go.(*uniStreamSender).onStreamCompleted(0xc420590000, 0x2d)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/stream.go:41 +0x29
github.com/lucas-clemente/quic-go.(*receiveStream).Read(0xc420654000, 0xc420870000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/receive_stream.go:161 +0x606
io/ioutil.devNull.ReadFrom(0x0, 0x2a8c4c0, 0xc420654000, 0x12aa680, 0xc42094cf01, 0x2a0a170)
    /usr/local/Cellar/go/1.10/libexec/src/io/ioutil/ioutil.go:147 +0x92
io.copyBuffer(0x1335fe0, 0x14c5860, 0x2a8c4c0, 0xc420654000, 0x0, 0x0, 0x0, 0x12592e5, 0xc420478800, 0x0)
    /usr/local/Cellar/go/1.10/libexec/src/io/io.go:386 +0x31a
io.Copy(0x1335fe0, 0x14c5860, 0x2a8c4c0, 0xc420654000, 0x0, 0x0, 0x37)
    /usr/local/Cellar/go/1.10/libexec/src/io/io.go:362 +0x5a
created by github.com/ltucker/quic_deadlock.TestSessionDeadlock.func1
    /Users/ltucker/go/src/github.com/ltucker/quic_deadlock/deadlock_test.go:75 +0x257

goroutine 106267 [semacquire, 9 minutes]:
sync.runtime_SemacquireMutex(0xc420654004, 0xc4204b9a00)
    /usr/local/Cellar/go/1.10/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420654000)
    /usr/local/Cellar/go/1.10/libexec/src/sync/mutex.go:134 +0x108
github.com/lucas-clemente/quic-go.(*receiveStream).closeForShutdown(0xc420654000, 0x13357e0, 0xc4208d2460)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/receive_stream.go:267 +0x2d
github.com/lucas-clemente/quic-go.(*stream).closeForShutdown(0xc420654000, 0x13357e0, 0xc4208d2460)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/stream.go:153 +0x6a
github.com/lucas-clemente/quic-go.(*streamsMapLegacy).CloseWithError(0xc420740380, 0x13357e0, 0xc4208d2460)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/streams_map_legacy.go:256 +0x13d
github.com/lucas-clemente/quic-go.(*session).handleCloseError(0xc420711400, 0x1335f80, 0x0, 0xc4204b9c00, 0x27f00dca4, 0x14a83c0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/session.go:839 +0x16f
github.com/lucas-clemente/quic-go.(*session).run(0xc420711400, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/session.go:535 +0xeec
github.com/lucas-clemente/quic-go.(*client).establishSecureConnection.func1(0xc420804820, 0xc4205cce00, 0xc4200b65a0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/client.go:251 +0x41
created by github.com/lucas-clemente/quic-go.(*client).establishSecureConnection
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/client.go:250 +0xa3
```

**Comment by marten-seemann** [comment]
Hi @ltucker, thanks for reporting this! The test case is super helpful.

I'm currently traveling, so it might take a couple of days until I can review your PR.
