### ISSUE TITLE
start listening after creating the client session

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#1418]
If done the other way round, this can lead to panics:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x13ba814]

goroutine 12 [running]:
github.com/lucas-clemente/quic-go.(*client).handleGQUICPacket(0xc42034f790, 0xc42019e000, 0xc42034f790, 0x1c01458)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/client.go:460 +0x74
github.com/lucas-clemente/quic-go.(*client).handlePacketImpl(0xc42034f790, 0xc42019e000, 0x0, 0x0)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/client.go:395 +0x18a
github.com/lucas-clemente/quic-go.(*client).handlePacket(0xc42034f790, 0xc42019e000)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/client.go:366 +0x39
github.com/lucas-clemente/quic-go.(*clientMultiplexer).listen(0xc420361a40, 0x164a7a0, 0xc4200dbe00, 0x1649380, 0xc4203498c0)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/client_multiplexer.go:89 +0x473
created by github.com/lucas-clemente/quic-go.(*clientMultiplexer).Add
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/client_multiplexer.go:55 +0x198

Tests failed on attempt #776
```

**Comment by marten-seemann** [comment]
We're now setting the `client.session` before calling `packetHandlerMap.Add`, so this issue should be fixed.

**Comment by neil88** [comment]
That's what happened to me, anyone who can tell me how to fix it
