### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by xjtdy888** [lucas-clemente/quic-go#2001]
Panic occurs after updating to master(1441923ab031d1e05a31045c41c3d65597c47c1a),   v0.11.2 is worked

```
panic: runtime error: index out of range

goroutine 2262 [running]:
/go/path/github.com/marten-seemann/qtls.(*Conn).encryptTicket(0xc004183880, 0xc004ae3340, 0x1b0, 0x1c0, 0x1, 0xc002c77960, 0x0, 0x1, 0x0)
	/go/path/github.com/marten-seemann/qtls/ticket.go:161 +0x4a3
/go/path/github.com/marten-seemann/qtls.(*Conn).GetSessionTicket(0xc004183880, 0xc0054a9f50, 0xc0054a9e98, 0xc0041f3bb8, 0xc0054a9eb8, 0xad0668)
	//go/path/github.com/marten-seemann/qtls/ticket.go:245 +0x30a
/go/path/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).maybeSendSessionTicket(0xc000523e00)
	/go/path/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup.go:456 +0x3a
/go/path/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).RunHandshake(0xc000523e00)
	/go/path/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup.go:273 +0x2d7
created by /go/path/github.com/lucas-clemente/quic-go.(*session).run
	/go/path/github.com/lucas-clemente/quic-go/session.go:373 +0x9e
```

**Comment by marten-seemann** [comment]
Can you tell me how exactly to reproduce this?

**Comment by marten-seemann** [comment]
@xjtdy888 Can you help me with this? I can't reproduce the bug, so I won't be able to fix it.

**Comment by xjtdy888** [comment]
I am doing a minimization test, I have no way to reproduce the process, only the integration into the existing project will trigger the panic.

**Comment by marten-seemann** [comment]
I managed to reproduce the bug by settings `tls.Config.SessionTicketDisabled = true` for the server.
