### ISSUE TITLE
echoServer , I replace the generateTLSConfig rsa to ed25519 , but panic: CRYPTO_ERROR: tls: internal error

### ISSUE THREAD

**Issue by i6du** [lucas-clemente/quic-go#2006]
go version go1.13beta1 darwin/amd64  ( ed25519 x509 supported in go1.13beta1 )

code is here https://github.com/i6du/test-quic

echoServer , I replace the generateTLSConfig rsa to ed25519

```
func generateTLSConfig() *tls.Config {

	max := new(big.Int)
	max.Exp(big.NewInt(2), big.NewInt(128), nil).Sub(max, big.NewInt(1))
	salt, err := rand.Int(rand.Reader, max)
	ex.Panic(err)

	template := x509.Certificate{SerialNumber: salt}

	pubKey, private, err := ed25519.GenerateKey(rand.Reader)

	ex.Panic(err)

	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, pubKey, private)
	ex.Panic(err)

	privateByte, err := x509.MarshalPKCS8PrivateKey(private)
	ex.Panic(err)

	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: privateByte})
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})

	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		panic(err)
	}

	return &tls.Config{
		Certificates: []tls.Certificate{tlsCert},
		NextProtos:   []string{"quic-echo-example"},
	}
}
```

but there is error `panic: CRYPTO_ERROR: tls: internal error` on line 	
```
session, err := quic.DialAddr(addr, tlsConf, nil)
```

**Comment by marten-seemann** [comment]
Please run both server and client with [logging](https://github.com/lucas-clemente/quic-go/wiki/Logging) and post the logs here.

**Comment by i6du** [comment]
log here , just run server , panic happened

➜  test git:(master) ✗ export QUIC_GO_LOG_LEVEL=DEBUG   
➜  test git:(master) ✗ go run main.go                
```
2019/07/17 01:08:06 client Starting new connection to localhost ([::]:54018 -> 127.0.0.1:4242), source connection ID (empty), destination connection ID 0x0305c4027878d1455dc8f51e, version QUIC WG draft-19
2019/07/17 01:08:06 server Listening for udp connections on 127.0.0.1:4242
2019/07/17 01:08:06 client -> Sending packet 0x0 (1200 bytes) for connection (empty), Initial
2019/07/17 01:08:06 client      Long Header{Type: Initial, DestConnectionID: 0x0305c4027878d1455dc8f51e, SrcConnectionID: (empty), Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 1179, Version: QUIC WG draft-19}
2019/07/17 01:08:06 client      -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x158, Offset + Data length: 0x158}
2019/07/17 01:08:06 server <- Received Initial packet.
2019/07/17 01:08:06 server      Long Header{Type: Initial, DestConnectionID: 0x0305c4027878d1455dc8f51e, SrcConnectionID: (empty), Token: (empty), PacketNumber: 0x0, PacketNumberLen: 0, Length: 1179, Version: QUIC WG draft-19}
2019/07/17 01:08:06 server Changing connection ID to 0x0f5cee30.
-> Sending Retry
2019/07/17 01:08:06 server      Long Header{Type: Retry, DestConnectionID: (empty), SrcConnectionID: 0x0f5cee30, Token: 0xbd98f712ca6bf51816b46774995e133e416ab3ed30707babecd61398b2fda9b54592676a93c9453b89d7c55917e6cd8241862a8f38710a51790be204e324f1b4ac4baa8ee00f21c8ab3bb4abad, OrigDestConnectionID: 0x0305c4027878d1455dc8f51e, Version: QUIC WG draft-19}
2019/07/17 01:08:06 client      Long Header{Type: Retry, DestConnectionID: (empty), SrcConnectionID: 0x0f5cee30, Token: 0xbd98f712ca6bf51816b46774995e133e416ab3ed30707babecd61398b2fda9b54592676a93c9453b89d7c55917e6cd8241862a8f38710a51790be204e324f1b4ac4baa8ee00f21c8ab3bb4abad, OrigDestConnectionID: 0x0305c4027878d1455dc8f51e, Version: QUIC WG draft-19}
2019/07/17 01:08:06 client <- Received Retry
2019/07/17 01:08:06 client Switching destination connection ID to: 0x0f5cee30
2019/07/17 01:08:06 client Queueing packet 0x0 for retransmission.
2019/07/17 01:08:06 client Dequeueing retransmission for packet 0x0 (Initial)
2019/07/17 01:08:06 client -> Sending packet 0x1 (1200 bytes) for connection (empty), Initial
2019/07/17 01:08:06 client      Long Header{Type: Initial, DestConnectionID: 0x0f5cee30, SrcConnectionID: (empty), Token: 0xbd98f712ca6bf51816b46774995e133e416ab3ed30707babecd61398b2fda9b54592676a93c9453b89d7c55917e6cd8241862a8f38710a51790be204e324f1b4ac4baa8ee00f21c8ab3bb4abad, PacketNumber: 0x1, PacketNumberLen: 4, Length: 1109, Version: QUIC WG draft-19}
2019/07/17 01:08:06 client      -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x158, Offset + Data length: 0x158}
2019/07/17 01:08:06 server <- Received Initial packet.
2019/07/17 01:08:06 server Changing connection ID to 0x8821648a.
2019/07/17 01:08:06 server <- Reading packet 0x1 (1200 bytes) for connection 0x0f5cee30, Initial
2019/07/17 01:08:06 server      Long Header{Type: Initial, DestConnectionID: 0x0f5cee30, SrcConnectionID: (empty), Token: 0xbd98f712ca6bf51816b46774995e133e416ab3ed30707babecd61398b2fda9b54592676a93c9453b89d7c55917e6cd8241862a8f38710a51790be204e324f1b4ac4baa8ee00f21c8ab3bb4abad, PacketNumber: 0x1, PacketNumberLen: 4, Length: 1109, Version: QUIC WG draft-19}
2019/07/17 01:08:06 server      <- &wire.CryptoFrame{Offset: 0x0, Data length: 0x158, Offset + Data length: 0x158}
2019/07/17 01:08:06 server Received ClientHello message (344 bytes, encryption level: Initial)
2019/07/17 01:08:06 server Closing session with error: CRYPTO_ERROR: tls: unsupported certificate key (ed25519.PublicKey)
2019/07/17 01:08:06 server Received Transport Parameters: &handshake.TransportParameters{OriginalConnectionID: (empty), InitialMaxStreamDataBidiLocal: 0x80000, InitialMaxStreamDataBidiRemote: 0x80000, InitialMaxStreamDataUni: 0x80000, InitialMaxData: 0xc0000, MaxBidiStreams: 100, MaxUniStreams: 100, IdleTimeout: 30s, AckDelayExponent: 3}
2019/07/17 01:08:06 server Handled crypto frame at level Initial. encLevelChanged: false
2019/07/17 01:08:06 server      Queueing ACK because the first packet should be acknowledged.
2019/07/17 01:08:06 server -> Sending packet 0x0 (38 bytes) for connection 0x8821648a, Initial
2019/07/17 01:08:06 server      Long Header{Type: Initial, DestConnectionID: (empty), SrcConnectionID: 0x8821648a, Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 26, Version: QUIC WG draft-19}
2019/07/17 01:08:06 server      -> &wire.AckFrame{LargestAcked: 0x1, LowestAcked: 0x1, DelayTime: 2.919581ms}
2019/07/17 01:08:06 server -> Sending packet 0x1 (37 bytes) for connection 0x8821648a, Initial
2019/07/17 01:08:06 server      Long Header{Type: Initial, DestConnectionID: (empty), SrcConnectionID: 0x8821648a, Token: (empty), PacketNumber: 0x1, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-19}
2019/07/17 01:08:06 server      -> &wire.ConnectionCloseFrame{IsApplicationError:false, ErrorCode:0x150, ReasonPhrase:""}
2019/07/17 01:08:06 server Connection 0x8821648a closed.
2019/07/17 01:08:06 client <- Reading packet 0x0 (38 bytes) for connection (empty), Initial
2019/07/17 01:08:06 client      Long Header{Type: Initial, DestConnectionID: (empty), SrcConnectionID: 0x8821648a, Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 26, Version: QUIC WG draft-19}
2019/07/17 01:08:06 client Received first packet. Switching destination connection ID to: 0x8821648a
2019/07/17 01:08:06 client      <- &wire.AckFrame{LargestAcked: 0x1, LowestAcked: 0x1, DelayTime: 2.912ms}
2019/07/17 01:08:06 client      updated RTT: 6.340047ms (σ: 3.170023ms)
2019/07/17 01:08:06 client      newly acked packets (1): [0x1]
2019/07/17 01:08:06 client      Queueing ACK because the first packet should be acknowledged.
2019/07/17 01:08:06 client -> Sending packet 0x2 (1200 bytes) for connection (empty), Initial
2019/07/17 01:08:06 client      Long Header{Type: Initial, DestConnectionID: 0x8821648a, SrcConnectionID: (empty), Token: 0xbd98f712ca6bf51816b46774995e133e416ab3ed30707babecd61398b2fda9b54592676a93c9453b89d7c55917e6cd8241862a8f38710a51790be204e324f1b4ac4baa8ee00f21c8ab3bb4abad, PacketNumber: 0x2, PacketNumberLen: 4, Length: 1109, Version: QUIC WG draft-19}
2019/07/17 01:08:06 client      -> &wire.AckFrame{LargestAcked: 0x0, LowestAcked: 0x0, DelayTime: 883.898µs}
2019/07/17 01:08:06 client <- Reading packet 0x1 (37 bytes) for connection (empty), Initial
2019/07/17 01:08:06 client      Long Header{Type: Initial, DestConnectionID: (empty), SrcConnectionID: 0x8821648a, Token: (empty), PacketNumber: 0x1, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-19}
2019/07/17 01:08:06 client      <- &wire.ConnectionCloseFrame{IsApplicationError:false, ErrorCode:0x150, ReasonPhrase:""}
2019/07/17 01:08:06 client Peer closed session with error: CRYPTO_ERROR: tls: internal error
2019/07/17 01:08:06 server Received 1 packets after sending CONNECTION_CLOSE. Retransmitting.
2019/07/17 01:08:06 client      Setting ACK timer to max ack delay: 25ms
2019/07/17 01:08:06 client      Setting ACK timer to 1/8 min-RTT: 792.505µs (-1.06816ms from now)
2019/07/17 01:08:06 client Sending ACK because the ACK timer expired.
2019/07/17 01:08:06 client -> Sending packet 0x3 (1200 bytes) for connection (empty), Initial
2019/07/17 01:08:06 client      Long Header{Type: Initial, DestConnectionID: 0x8821648a, SrcConnectionID: (empty), Token: 0xbd98f712ca6bf51816b46774995e133e416ab3ed30707babecd61398b2fda9b54592676a93c9453b89d7c55917e6cd8241862a8f38710a51790be204e324f1b4ac4baa8ee00f21c8ab3bb4abad, PacketNumber: 0x3, PacketNumberLen: 4, Length: 1109, Version: QUIC WG draft-19}
2019/07/17 01:08:06 client      -> &wire.AckFrame{LargestAcked: 0x1, LowestAcked: 0x0, DelayTime: 1.869396ms}
2019/07/17 01:08:06 muxer received a packet with an unexpected connection ID (empty)
2019/07/17 01:08:06 client Connection (empty) closed.
2019/07/17 01:08:06 server Received 2 packets after sending CONNECTION_CLOSE. Retransmitting.
panic: CRYPTO_ERROR: tls: internal error

goroutine 1 [running]:
github.com/u6du/ex.Panic(...)
        /Users/z/go/pkg/mod/github.com/u6du/ex@v0.0.0-20190711032711-9e0cd89c4843/ex.go:7
main.clientMain(0x0, 0x12c9550)
        /Users/z/git/6du/test/main.go:57 +0x3f0
main.main()
        /Users/z/git/6du/test/main.go:29 +0x3a
exit status 2
```

**Comment by marten-seemann** [comment]
```
2019/07/17 01:08:06 server Closing session with error: CRYPTO_ERROR: tls: unsupported certificate key (ed25519.PublicKey)
```

ed25519 is not support by the TLS library used by quic-go yet.

**Comment by postables** [comment]
@marten-seemann any updates on this? go 1.13 is now released
