### ISSUE TITLE
panic: bytes: negative Repeat count

### ISSUE THREAD

**Issue by xjtdy888** [lucas-clemente/quic-go#2140]
```
panic: bytes: negative Repeat count

goroutine 1062 [running]:
bytes.Repeat(0xc000e8f8df, 0x1, 0x1, 0xffffffffffffff2d, 0x0, 0xc0001d4480, 0xc004773930)        /usr/local/go/src/bytes/bytes.go:499 +0x1ab
github.com/lucas-clemente/quic-go.(*packetPacker).writeAndSealPacketWithPadding(0xc00007bee0, 0xc0001d4480, 0xc000c86b60, 0x1, 0x1, 0x0, 0x147, 0xffffffffffffff2d, 0x1, 0x20967e8, ...)
        /Users/coder/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/packet_packer.go:539 +0x753
github.com/lucas-clemente/quic-go.(*packetPacker).writeAndSealPacket(0xc00007bee0, 0xc0001d4480, 0xc000c86b60, 0x1, 0x1, 0x0, 0x147, 0x1, 0x20967e8, 0xc0006619a0, ...)
        /Users/coder/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/packet_packer.go:515 +0x182
github.com/lucas-clemente/quic-go.(*packetPacker).PackRetransmission(0xc00007bee0, 0xc000da22d8, 0x2e, 0xc00409a020, 0x2, 0x2, 0x1)
        /Users/coder/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/packet_packer.go:300 +0x615
github.com/lucas-clemente/quic-go.(*session).maybeSendRetransmission(0xc000907b00, 0x1, 0xc003e34432, 0xc003e34000)        /Users/coder/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/session.go:1120 +0x159
github.com/lucas-clemente/quic-go.(*session).sendPackets(0xc000907b00, 0x7be98f435, 0x1b54be0)
        /Users/coder/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/session.go:1065 +0x2ebgithub.com/lucas-clemente/quic-go.(*session).run(0xc000907b00, 0x0, 0x0)
        /Users/coder/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/session.go:456 +0x58c
github.com/lucas-clemente/quic-go.(*client).establishSecureConnection.func1(0xc00007be10, 0xc0026fa000)        /Users/coder/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/client.go:281 +0x48
created by github.com/lucas-clemente/quic-go.(*client).establishSecureConnection
        /Users/coder/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/client.go:280 +0x83
```

**Comment by marten-seemann** [comment]
We recently refactored how retransmissions are sent, so this won't apply to the master branch any more.
