### ISSUE TITLE
race condition in http3.body.requestDone()

### ISSUE THREAD

**Issue by fbzhong** [lucas-clemente/quic-go#2143]
I encountered a crash bug, call stack is the following:
```
panic: close of closed channel

goroutine 83814 [running]:
github.com/lucas-clemente/quic-go/http3.(*body).requestDone(...)
	github.com/lucas-clemente/quic-go/http3/body.go:85
github.com/lucas-clemente/quic-go/http3.(*body).Close(0x400128d9b0, 0x4001223140, 0x48400)
	github.com/lucas-clemente/quic-go/http3/body.go:94 +0x5c
client.(*DeadlineReader).Close(0x40005e0140, 0x216cd4ff97d2, 0x745c043800)
	client/deadline_readwriter.go:72 +0x60
```

body.go:85
https://github.com/lucas-clemente/quic-go/blob/07ee05b5a967d37650cb32109f9dc15d72e300f7/http3/body.go#L81-L87

The code of client/deadline_readwriter.go:72
```
func (r *DeadlineReader) Close() (err error) {
	select {
	case <-r.closed:
		return ErrClosedPipe
	default:
	}

	close(r.closed)

	if r.lastResult != nil {
		r.bufPool.Put(r.lastResult.buf)
		r.lastResult = nil
	}

	return r.rd.Close()
}
```

I take a look at the body.go. The `body.requestDone()` are called at two position:
1. `body.Close()`
2. 'body.Read()`
So when one goroutine call Read(), the other is calling Close(), and there is no lock inside `requestDone()`, crash will happen.

**Comment by marten-seemann** [comment]
Thanks for finding this.

There are two things that are suboptimal in this code:
1. `Read` should probably check that the error is not `io.EOF` before calling `requestDone`.
2. `requestDone` should use a `sync.Once` instead of a `bool`.

**Comment by fbzhong** [comment]
Ok, I will send a PR later soon.

**Comment by fbzhong** [comment]
@marten-seemann I think we should call `requestDone` whenever error occurs. For a blocking reader, `io.EOF` means reader is at end, it's time to close it.

**Comment by marten-seemann** [comment]
It actually doesn't make a big difference, since the caller will call `http.Response.Close()` anyway after reading the body.

**Comment by marten-seemann** [comment]
Actually, thinking about this a bit more, I don't think this is a bug in quic-go after all. 

`Read` and `Close` shouldn't be called concurrently, so it's not quic-go's fault if you introduce a race condition like this.

**Comment by fbzhong** [comment]
Hi, I describe a user scenario:

We build a http3 enabled proxy. Accept a req, then forward to remote http3 server. In this case, we handle both read and write in two conn, one is tcp conn, the other is http3 req/resp body. 
We need to handle the tcp conn closed event, and then to close http3 resp body to quit read/write goroutine. 
So, we may encounter this case:
1) tcp conn is closed , we call “http3.body.Close()”
2) at the same time, underlying Quic session is closed as well, network error or timeout. The “body.requestDone()” is called when “read” return error. 
As we see, chan will be closed twice, app crashes. 


I think the root cause is “body.Read” is blocking read, there is no way to return from Read, except Close it. Either way we need another goroutine to call for that, race condition will be definitely encountered.

**Comment by fbzhong** [comment]
@marten-seemann I'd like you reconsider this issue.

**Comment by marten-seemann** [comment]
I still don’t see the problem here. It looks like you’re calling Read and Close concurrently, so you’re responsible for creating the race condition yourself.

**Comment by fbzhong** [comment]
So, can you please let me know how to solve that issue? When “read()” is blocking, how to force break the “read” goroutine before the underlying timeout of Quic-go without crash? The other Blocking network library do support concurrent read and close. 

According to your reply, do you suggest to wait to timeout?

**Comment by marten-seemann** [comment]
Using `Close` to unblock `Read` is not the expected behavior in Go.

**Comment by fbzhong** [comment]
Thanks for your reply. Can u share me the expected behavior for this scenario in go?

**Comment by fbzhong** [comment]
@marten-seemann can you spend some time to let me know more about that scenario? Really appreciate. Thanks.

**Comment by mmmray** [comment]
FWIW http2 does not exhibit this behavior during streaming responses, so it's a bit irritating to have to deal with different behavior per-http-version.

**Comment by mmmray** [comment]
I'd also like this behavior to be reconsidered. Both h1/h2 transports handle Close+Read without crashing, but h3 does not. This inconsistency makes it difficult to handle all HTTP versions transparently in application code that already relies on this behavior.

The workaround I have so far is to wrap `response.Body` in this struct:

```go

type h3Body struct {
	inner  io.ReadCloser
	lock   sync.Mutex
	cancel context.CancelFunc
}

func (c *h3Body) Read(b []byte) (int, error) {
	c.lock.Lock()
	defer c.lock.Unlock()

	return c.inner.Read(b)
}

func (c *h3Body) Close() error {
	c.cancel()

	c.lock.Lock()
	defer c.lock.Unlock()

	return c.inner.Close()
}

ctx, ctxCancel := context.WithCancel(context.Background())
req, err := http.NewRequestWithContext(ctx, ...)

...

response, err := client.Do(req)

...

body := h3Body { inner: response.Body, cancel: ctxCancel }
```

But clearly this comes with some overhead on Read.
