### ISSUE TITLE
lsquic client draft-23/24 can't handshake successful with quic-go v0.13.1/0.14.0

### ISSUE THREAD

**Issue by Zeymo** [lucas-clemente/quic-go#2256]
Isquic use borring-ssl  communicate with quic-go seems can't generator matched pair of  shareKey , so that quic-go will decrypto Handshake message error 
> server Dropping Handshake packet that could not be unpacked. Error: decryption failed

qtls do any specail logic in change shareKey ?  

snippet like 
https://github.com/marten-seemann/qtls/blob/6f6c03202c2cd1f60588fc703c2d15d12721c44d/handshake_server_tls13.go#L535-L536

https://github.com/marten-seemann/qtls/blob/6f6c03202c2cd1f60588fc703c2d15d12721c44d/handshake_server_tls13.go#L545-L550

I can't find same absolutely equation logic in 49de1fc2910524c888866c7e2b0db1ba8af2a530 of borring-ssl which lsquic used

**Comment by tohutohu** [comment]
Same with aioquic.
```
2019-12-06 01:33:28,694 DEBUG asyncio Using selector: KqueueSelector
2019-12-06 01:33:28,834 DEBUG quic [6f7260c3d849d695] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2019-12-06 01:33:28,834 INFO quic [6f7260c3d849d695] Performing stateless retry
2019-12-06 01:33:28,836 DEBUG quic [6f7260c3d849d695] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2019-12-06 01:33:28,839 DEBUG quic [6f7260c3d849d695] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2019-12-06 01:33:28,839 DEBUG quic [6f7260c3d849d695] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2019-12-06 01:33:28,840 DEBUG quic [6f7260c3d849d695] TLS State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS -> State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE
2019-12-06 01:33:28,840 DEBUG quic [6f7260c3d849d695] Discarding epoch Epoch.INITIAL
2019-12-06 01:33:28,841 DEBUG quic [6f7260c3d849d695] TLS State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE -> State.CLIENT_EXPECT_CERTIFICATE_VERIFY
2019-12-06 01:33:28,873 WARNING quic [6f7260c3d849d695] Error: 298, reason: unable to get local issuer certificate, frame_type: 6
2019-12-06 01:33:28,878 DEBUG quic [6f7260c3d849d695] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
2019-12-06 01:33:28,878 DEBUG quic [6f7260c3d849d695] Discarding epoch Epoch.INITIAL
2019-12-06 01:33:28,984 DEBUG quic [6f7260c3d849d695] Discarding epoch Epoch.INITIAL
2019-12-06 01:33:28,984 DEBUG quic [6f7260c3d849d695] Discarding epoch Epoch.HANDSHAKE
2019-12-06 01:33:28,984 DEBUG quic [6f7260c3d849d695] Discarding epoch Epoch.ONE_RTT
2019-12-06 01:33:28,984 DEBUG quic [6f7260c3d849d695] QuicConnectionState.CLOSING -> QuicConnectionState.TERMINATED
Traceback (most recent call last):
  File "http3_client.py", line 412, in <module>
    print_response=args.print_response,
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "http3_client.py", line 307, in run
    session_ticket_handler=save_session_ticket,
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/Users/to-hutohu/Workspace/dynamic-alt-svc/aioquic/src/aioquic/asyncio/client.py", line 77, in connect
    await protocol.wait_connected()
  File "/Users/to-hutohu/Workspace/dynamic-alt-svc/aioquic/src/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError

2019/12/06_01:33:29 a-2.local:~/Workspace/dynamic-alt-svc/aioquic/examples
[to-hutohu@ examples] (master=)$ python3 http3_client.py --print-response https://q.to-hutohu.com:4433/ping
2019-12-06 01:33:56,011 INFO quic [52b6b9aa1c456d4b] Performing stateless retry
2019-12-06 01:33:56,045 WARNING quic [52b6b9aa1c456d4b] Error: 298, reason: unable to get local issuer certificate, frame_type: 6
Traceback (most recent call last):
  File "http3_client.py", line 412, in <module>
    print_response=args.print_response,
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "http3_client.py", line 307, in run
    session_ticket_handler=save_session_ticket,
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/Users/to-hutohu/Workspace/dynamic-alt-svc/aioquic/src/aioquic/asyncio/client.py", line 77, in connect
    await protocol.wait_connected()
  File "/Users/to-hutohu/Workspace/dynamic-alt-svc/aioquic/src/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError
```

Ignoring the certificate will not cause an error
```
2019-12-06 01:35:44,444 DEBUG asyncio Using selector: KqueueSelector
2019-12-06 01:35:44,484 DEBUG quic [8aaec3ce2b18f8ba] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2019-12-06 01:35:44,485 INFO quic [8aaec3ce2b18f8ba] Performing stateless retry
2019-12-06 01:35:44,487 DEBUG quic [8aaec3ce2b18f8ba] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2019-12-06 01:35:44,489 DEBUG quic [8aaec3ce2b18f8ba] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2019-12-06 01:35:44,490 DEBUG quic [8aaec3ce2b18f8ba] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2019-12-06 01:35:44,490 DEBUG quic [8aaec3ce2b18f8ba] TLS State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS -> State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE
2019-12-06 01:35:44,490 DEBUG quic [8aaec3ce2b18f8ba] Discarding epoch Epoch.INITIAL
2019-12-06 01:35:44,491 DEBUG quic [8aaec3ce2b18f8ba] TLS State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE -> State.CLIENT_EXPECT_CERTIFICATE_VERIFY
2019-12-06 01:35:44,491 DEBUG quic [8aaec3ce2b18f8ba] TLS State.CLIENT_EXPECT_CERTIFICATE_VERIFY -> State.CLIENT_EXPECT_FINISHED
2019-12-06 01:35:44,492 DEBUG quic [8aaec3ce2b18f8ba] TLS State.CLIENT_EXPECT_FINISHED -> State.CLIENT_POST_HANDSHAKE
2019-12-06 01:35:44,492 INFO quic [8aaec3ce2b18f8ba] ALPN negotiated protocol h3-24
2019-12-06 01:35:44,492 DEBUG quic [8aaec3ce2b18f8ba] Discarding epoch Epoch.INITIAL
2019-12-06 01:35:44,493 DEBUG quic [8aaec3ce2b18f8ba] Decryption key is not available
2019-12-06 01:35:44,493 DEBUG quic [8aaec3ce2b18f8ba] Decryption key is not available
2019-12-06 01:35:44,494 DEBUG quic [8aaec3ce2b18f8ba] Discarding epoch Epoch.HANDSHAKE
2019-12-06 01:35:44,494 DEBUG quic [8aaec3ce2b18f8ba] Peer retiring CID 341a306545c05b5e (0)
2019-12-06 01:35:44,494 INFO client New session ticket received
2019-12-06 01:35:44,495 DEBUG quic [8aaec3ce2b18f8ba] Stream 3 created by peer
2019-12-06 01:35:44,496 INFO client Received 4 bytes in 0.0 s (0.012 Mbps)
2019-12-06 01:35:44,496 DEBUG quic [8aaec3ce2b18f8ba] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
2019-12-06 01:35:44,594 DEBUG quic [8aaec3ce2b18f8ba] Discarding epoch Epoch.INITIAL
2019-12-06 01:35:44,594 DEBUG quic [8aaec3ce2b18f8ba] Discarding epoch Epoch.HANDSHAKE
2019-12-06 01:35:44,595 DEBUG quic [8aaec3ce2b18f8ba] Discarding epoch Epoch.ONE_RTT
2019-12-06 01:35:44,595 DEBUG quic [8aaec3ce2b18f8ba] QuicConnectionState.CLOSING -> QuicConnectionState.TERMINATED
```

Chromium 80.0.3987.0（Developer Build）with args "--enable-quic --quic-version=h3-24" too could not be connected.

**Comment by marten-seemann** [comment]
quic-go client successfully handshakes with an lsquic server. Furthermore, quic-go has interoperability based on draft-24 with at least 6 other QUIC implementation. I suggest you raise this issue with lsquic / aioquic.

**Comment by initlifeinc** [comment]
hi, please check this issue, https://github.com/litespeedtech/lsquic/issues/92

it seems quic-go server did not return the handshake packet.  do you have some any suggestions?

**Comment by dtikhonov** [comment]
> it seems quic-go server did not return the handshake packet. do you have some any suggestions?

Handshake succeeds, the server does not return an HTTP response.

Anyway, a beer says that the problem is in the quic-go server rather than the lsquic client.  What say you, @marten-seemann?

**Comment by initlifeinc** [comment]
we have create a temp quic-go server, use example/main.go to build and deploy.
use httpclient of lsquic example to connect.
./http_client -H quic-go.server.com -s 192.119.67.12:6121 -p / -L debug

**Comment by marten-seemann** [comment]
> Anyway, a beer says that the problem is in the quic-go server rather than the lsquic client. What say you, @marten-seemann?

@dtikhonov That’s hard to tell without being able to reproduce the problem. I don’t have an lsquic client to play around with. Would be easy if lsquic was on the interop runner...

**Comment by initlifeinc** [comment]
i have already debug to find the clientHandshake key and serverHandshake key calculate by lsquic is equal to the value of clientSecret and serverSecret calculated in handshake_server_tls13.go

	clientSecret := hs.suite.deriveSecret(hs.handshakeSecret,
		clientHandshakeTrafficLabel, hs.transcript)
	c.in.exportKey(EncryptionHandshake, hs.suite, clientSecret)
	c.in.setTrafficSecret(hs.suite, clientSecret)
	serverSecret := hs.suite.deriveSecret(hs.handshakeSecret,
		serverHandshakeTrafficLabel, hs.transcript)
	c.out.exportKey(EncryptionHandshake, hs.suite, serverSecret)
	c.out.setTrafficSecret(hs.suite, serverSecret)

.

but when quic-go receive the handshake packet sent from lsquic, it can parse the header success, but failed to run this code. 
	decrypted, err := opener.Open(data[extHdrLen:extHdrLen], data[extHdrLen:], extHdr.PacketNumber, data[:extHdrLen])


....much more infos will be attached later

**Comment by marten-seemann** [comment]
@Zeymo Can you post a debug log of the quic-go server?

**Comment by Zeymo** [comment]
@marten-seemann  I fixed the issue above, and request will success
I  truelly because the read length VarInt,I will post a PR to fix it

#2259
