### ISSUE TITLE
qlog panic

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#2578]
When running with aioquic.

```
client          | Test case: handshake
client          | panic: runtime error: invalid memory address or nil pointer dereference
client          | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x79dd4c]
client          | 
client          | goroutine 10 [running]:
client          | github.com/lucas-clemente/quic-go/qlog.eventTransportParameters.MarshalJSONObject(0x1, 0x1, 0xc0000b40c0, 0x12, 0x12, 0xc0000a6210, 0x8, 0x8, 0x0, 0x0, ...)
client          | 	/quic-go/qlog/event.go:360 +0x47c
client          | github.com/francoispqt/gojay.(*Encoder).Object(0xc0000941e0, 0x7f67f2f810a0, 0xc0000d0000)
client          | 	/root/go/pkg/mod/github.com/francoispqt/gojay@v1.2.13/encode_object.go:125 +0x3c7
client          | github.com/lucas-clemente/quic-go/qlog.event.MarshalJSONArray(0x267d3692, 0xaba780, 0xc0000d0000, 0xc0000941e0)
client          | 	/quic-go/qlog/event.go:47 +0x103
client          | github.com/francoispqt/gojay.(*Encoder).encodeArray(0xc0000941e0, 0xab5960, 0xc000202200, 0x40bc43, 0x9692a0, 0x9b9940, 0xc000052e01, 0xab5960)
client          | 	/root/go/pkg/mod/github.com/francoispqt/gojay@v1.2.13/encode_array.go:19 +0x7f
client          | github.com/francoispqt/gojay.(*Encoder).EncodeArray(0xc0000941e0, 0xab5960, 0xc000202200, 0xab5960, 0xc000202200)
client          | 	/root/go/pkg/mod/github.com/francoispqt/gojay@v1.2.13/encode_array.go:8 +0x4d
client          | github.com/francoispqt/gojay.(*Encoder).Encode(0xc0000941e0, 0x9b9940, 0xc000202200, 0xc000202200, 0x1)
client          | 	/root/go/pkg/mod/github.com/francoispqt/gojay@v1.2.13/encode_interface.go:21 +0x67d
client          | github.com/lucas-clemente/quic-go/qlog.(*tracer).run(0xc0001a8000)
client          | 	/quic-go/qlog/qlog.go:110 +0x43c
client          | created by github.com/lucas-clemente/quic-go/qlog.NewTracer
client          | 	/quic-go/qlog/qlog.go:73 +0x14c
```

**Comment by marten-seemann** [comment]
This was introduced in #2567. Fixed in a rebase.
