### ISSUE TITLE
panic: congestion BUG: decreased max datagram size

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#3106]
```
panic: congestion BUG: decreased max datagram size

goroutine 22498 [running]:
github.com/lucas-clemente/quic-go/internal/congestion.(*cubicSender).SetMaxDatagramSize(0xc0037a2000, 0x4dd)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/internal/congestion/cubic_sender.go:286 +0x85
github.com/lucas-clemente/quic-go/internal/ackhandler.(*sentPacketHandler).SetMaxDatagramSize(0xc001ca1110, 0x4dd)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/internal/ackhandler/sent_packet_handler.go:712 +0x3e
github.com/lucas-clemente/quic-go.(*session).handleHandshakeComplete.func1(0x4dd)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/session.go:800 +0x4b
github.com/lucas-clemente/quic-go.(*mtuFinder).GetPing.func2(0x25e0080, 0x3321bb8)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/mtu_discoverer.go:81 +0x3a
github.com/lucas-clemente/quic-go/internal/ackhandler.(*sentPacketHandler).detectAndRemoveAckedPackets(0xc001ca1110, 0xc003a69f00, 0xde1c58b04, 0x32ee560, 0x150e63245, 0xf32abbdee, 0xc00d7e1d2be09fa9, 0xc002e0b5f0)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/internal/ackhandler/sent_packet_handler.go:396 +0x2ba
github.com/lucas-clemente/quic-go/internal/ackhandler.(*sentPacketHandler).ReceivedAck(0xc001ca1110, 0xc003a69f00, 0xc004003404, 0xc00d7e1d2bc243ef, 0xf328d6216, 0x32ee560, 0x1, 0x1)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/internal/ackhandler/sent_packet_handler.go:291 +0xc5
github.com/lucas-clemente/quic-go.(*session).handleAckFrame(0xc002941800, 0xc003a69f00, 0x25dfd04, 0xc003a69f00, 0x0)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/session.go:1363 +0x77
github.com/lucas-clemente/quic-go.(*session).handleFrame(0xc002941800, 0x25dfd40, 0xc003a69f00, 0xc003950004, 0xc001729450, 0x4, 0x4, 0x1, 0x17c7525)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/session.go:1197 +0xdc
github.com/lucas-clemente/quic-go.(*session).handleUnpackedPacket(0xc002941800, 0xc003f181e0, 0xc00d7e1d2bc24300, 0xc00d7e1d2bc243ef, 0xf328d6216, 0x32ee560, 0x25, 0x5ac, 0xc003f181e0)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/session.go:1179 +0x577
github.com/lucas-clemente/quic-go.(*session).handleSinglePacket(0xc002941800, 0xc002b48a20, 0xc003269b00, 0x0)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/session.go:980 +0xfab
github.com/lucas-clemente/quic-go.(*session).handlePacketImpl(0xc002941800, 0xc002b48a20, 0x6)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/session.go:889 +0x85
github.com/lucas-clemente/quic-go.(*session).run(0xc002941800, 0x0, 0x0)
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/session.go:612 +0x1005
created by github.com/lucas-clemente/quic-go.(*baseServer).handleInitialImpl
        pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/server.go:485 +0x478

**Comment by marten-seemann** [comment]
Update: adding more context to the panic reveals:
```
panic: congestion BUG: decreased max datagram size from 1252 to 1245
```

Looks like we're trying to decrease the packet size to below the initial packet size.

**Comment by marten-seemann** [comment]
Actually, not quite. This can only happen on IPv6 connections. There, we initially the MTU discoverer with the correct maximum packet size (1232 bytes), but we always use 1252 bytes to initialize the congestion controller.

The fix is to use the correct value to initialize the congestion controller.
