### ISSUE TITLE
caddy quic panic

### ISSUE THREAD

**Issue by kariedo** [lucas-clemente/quic-go#405]
Testing Caddy server with quic - it fails on some pages with the following error.
Is it something we can address here?

```
panic: interface conversion: io.ReadCloser is struct { io.Reader; io.Closer }, not *h2quic.requestBody
goroutine 44 [running]:
panic(0x85bf3e0, 0x18e63ca0)
        /usr/local/go/src/runtime/panic.go:500 +0x331
github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0x18d1ee40, 0x18d7b860, 0x18d79a80, 0x18e63600, 0x8869b80, 0x18c4fc00)
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:193 +0x174
created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:202 +0x85b
```

Thanks.

**Comment by marten-seemann** [comment]
The reason for this seems to be that in some cases, Caddy replaces the `request.Body`, for example in [httpserver/replacer.go#L91](https://github.com/mholt/caddy/blob/bbee961415ea829e632257f8e88fbbd0c8008f8e/caddyhttp/httpserver/replacer.go#L91).
