### ISSUE TITLE
Server sometimes aborts large downloads with an EOF error

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#59]

**Comment by lucas-clemente** [comment]
Trace of the Close(io.EOF):

```
panic: EOF

goroutine 11 [running]:
panic(0x773be0, 0xc820010110)
	/home/lucas/go/src/runtime/panic.go:481 +0x3e6
github.com/lucas-clemente/quic-go.(*Session).Close(0xc820b94f00, 0x7f088f925028, 0xc820010110, 0xc820011201, 0x0, 0x0)
	/home/lucas/src/go/src/github.com/lucas-clemente/quic-go/session.go:276 +0xc8
github.com/lucas-clemente/quic-go.(*Session).Run(0xc820b94f00)
	/home/lucas/src/go/src/github.com/lucas-clemente/quic-go/session.go:137 +0x4f3
created by github.com/lucas-clemente/quic-go.(*Server).handlePacket
	/home/lucas/src/go/src/github.com/lucas-clemente/quic-go/server.go:119 +0x705
exit status 2
´´´
