### ISSUE TITLE
panic in session

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#614]
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7041fb]
goroutine 7631 [running]:
panic(0x847240, 0xc420012190)
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/lucas-clemente/quic-go/qerr.ToQuicError(0x0, 0x0, 0xc428b0fd10)
	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/qerr/quic_error.go:44 +0xeb
github.com/lucas-clemente/quic-go.(*session).handleCloseError(0xc43b0adba0, 0x0, 0x0, 0x0, 0x0, 0xbc7040)
	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:562 +0x337
github.com/lucas-clemente/quic-go.(*session).run(0xc43b0adba0, 0xc430316fa0, 0x5dbeb5)
	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:308 +0x7fd
github.com/lucas-clemente/quic-go.(*client).createNewSession.func1(0xc431f28f00)
	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:271 +0x3e
created by github.com/lucas-clemente/quic-go.(*client).createNewSession
	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:283 +0x14b
```

**Comment by lucas-clemente** [comment]
Looks like handleCloseError should check whether the error is nil.

**Comment by marten-seemann** [comment]
`handleCloseError` should not be called with `nil`. We need to understand where the `nil` comes from.

**Comment by lucas-clemente** [comment]
This break in the runloop doesn't set the closeErr: https://github.com/lucas-clemente/quic-go/blob/222ffa2f4813c8e895250661988ca2f53ebd7e8c/session.go#L268

**Comment by marten-seemann** [comment]
I think we should do that there, instead of checking for `nil` in `handleCloseError`.
