### ISSUE TITLE
panic in packet packer

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#745]
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ddad5]

goroutine 36 [running]:
github.com/lucas-clemente/quic-go.(*packetPacker).writeAndSealPacket(0xc4201a8c00, 0xc42005e150, 0xc420018380, 0x1, 0x1, 0x0, 0x0, 0x14e32a0, 0xc420034c00, 0x1b7dc20, ...)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/packet_packer.go:311 +0x275
github.com/lucas-clemente/quic-go.(*packetPacker).PackConnectionClose(0xc4201a8c00, 0xc42000c240, 0xc42049aa00, 0x1954c40, 0xc42000c220)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/packet_packer.go:60 +0x106
github.com/lucas-clemente/quic-go.(*session).sendConnectionClose(0xc420491380, 0xc42000c220, 0xc42000c220, 0x1)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:702 +0xb1
github.com/lucas-clemente/quic-go.(*session).handleCloseError(0xc420491380, 0x1954c40, 0xc42000c220, 0xed0ffc000, 0xc415c92cb3, 0x1a56f20)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:581 +0x1b2
github.com/lucas-clemente/quic-go.(*session).run(0xc420491380, 0x1055ef1, 0xc4200119e0)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:335 +0xab9
github.com/lucas-clemente/quic-go.(*client).createNewSession.func1(0xc4201a8b80)
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/client.go:324 +0x38
created by github.com/lucas-clemente/quic-go.(*client).createNewSession
	/Users/marten/src/go/src/github.com/lucas-clemente/quic-go/client.go:333 +0x158
```

Apparently `writeAndSealPacket` is called with a `sealer` that is `nil`.

**Comment by marten-seemann** [comment]
I should make sure I working with a clean checkout 🤦‍♂️
