### ISSUE TITLE
Downgrade attack detected https://quic.clemente.io

### ISSUE THREAD

**Issue by gertcuykens** [lucas-clemente/quic-go#925]
```
% ./client https://quic.clemente.io
GET https://quic.clemente.io
Starting new connection to quic.clemente.io ([::]:63748 -> 188.68.52.107:443), connectionID 6ab3cffe43a41653, version gQUIC 39
Switching to QUIC version gQUIC 37. New connection ID: 217eaa71d5f9886e
Internal error: closing session in order to recreate it with a new version
Closing session with error: closing session in order to recreate it with a new version
Queueing packet 0x7 for later decryption
Closing session with error: VersionNegotiationMismatch: Downgrade attack detected
panic: Get https://quic.clemente.io: VersionNegotiationMismatch: Downgrade attack detected

goroutine 5 [running]:
main.main.func1(0xc420083260, 0xc42001a600, 0x7fff5fbff8c1, 0x18)
        /Users/gert/go/src/github.com/lucas-clemente/quic-go/example/client/main.go:37 +0x312
created by main.main
        /Users/gert/go/src/github.com/lucas-clemente/quic-go/example/client/main.go:34 +0x23b
%
```

**Comment by marten-seemann** [comment]
Hi @gertcuykens, thanks for reporting this!
I just reproduced this issue, and I'll debug and fix it later.

**Comment by gertcuykens** [comment]
No problem thanks for your awesome work on quic :) I hope google is sponsoring you for this because its a major step forward in ict technologie. I am working on a kubernetes yaml example to include
